### ISSUE TITLE
Incorrect display of “You” as all of display names when current user is not logged in

### ISSUE THREAD

**Issue by urbansheep** [clbn/freefeed-gamma#2]
When looking at the feed of a user or a group in not logged in mode (also tested in incognito mode in Firefox and Opera) all display names for all users and groups are shown as You in feed names, likes and comments.

Expected behavior is that display names show whatever actual display names set for each of the group and user.

**Screenshot:**
<img width="741" alt="2018-07-26 11 45 36" src="https://user-images.githubusercontent.com/1756417/43252791-09e20568-90cc-11e8-9adf-d6e528fa497f.png">

**Comment by clbn** [comment]
Sorry, I just saw this. Thanks for reporting. It was fixed in 24f3eae on 2018-07-26.
