### ISSUE TITLE
Order by display name on the groups/subscriptions page break things

### ISSUE THREAD

**Issue by fetsh** [clbn/freefeed-gamma#4]
When you click on "order by display name" link on your groups page (https://gamma.freefeed.net/groups) or on your subscriptions page (https://gamma.freefeed.net/clbn/subscriptions), page turns blank, and the browsers back button became broken, until refresh.

**Comment by clbn** [comment]
@fetsh Thanks for the report, I can reproduce this. Will be fixed soon.

**Comment by clbn** [comment]
@fetsh This is fixed now in version `2019.02.13`, please check if it's working for you.

**Comment by clbn** [comment]
In version `2019.02.14`, there's also a nice update for UX, see fb8a088:
```
Improve UX of sorting in TileUserList

Display alternative (more relevant) user names for specific sorting
modes.

I.e., for "Ordered by: username" option the list now shows usernames,
and for "Ordered by: display name" it shows display names instead. As
for chronological order, the list still uses your "Display preferences"
setting.
```

**Comment by fetsh** [comment]
Can confirm, everything works as expected with new UX improvements. Thanks!
